        SUBROUTINE ASSM(A,EK,NBAND,NEL)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C	ASSM ADDS EK AND EF TO GK AND GF GLOBAL MATRIX AND VECTOR             C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

	PARAMETER (MAXEQN=1001,MAXBND=40)
      	IMPLICIT DOUBLE PRECISION (A-H,O-Z)

	COMMON/PAR/QK(200),R,THETAW,DX,DT,NDT,NELEM,MAXITER,NPOL,IOUT,NL
	DIMENSION A(MAXEQN,MAXBND),EK(4,4)

	NDIAG = NBAND/2 + 1
	NRMAX=NEL+NPOL-1
	NCOL=NDIAG +1	
	K=0
	I=(NPOL-1)*NEL-NPOL+1
	DO 10 L=NEL,NRMAX
		I=I+1
		M=0
		K=K+1
		NCOL=NCOL-1
          	DO 10 J=NCOL,NCOL+NPOL-1
	       		M=M+1		
              		A(I,J) = A(I,J) + EK(K,M)
10   	CONTINUE

       	RETURN
      	END


