        SUBROUTINE FLOW(N,XT,QT)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C	Calculate the flow vector at each iteration or time step              C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

	PARAMETER (MAXEQN=1001,MAXBND=40)
	IMPLICIT DOUBLE PRECISION   (A-H,O-Z)

	COMMON/PAR/QK(200),R,THETAW,DX,DT,NDT,NELEM,MAXITER,NPOL,IOUT,NL
	DIMENSION XT(MAXEQN), QT(MAXEQN)
	fnoise=1.00D-06
		
	DO 10 I=1,N
		QT(I)=QK(I)*XT(I)**(5.D0/3.D0)
c-rmc 05/07/03 filter "noise" values from numerical oscillations
		if(qt(i).lt.fnoise) qt(i)=0.d0
10	CONTINUE

	RETURN
	END
 	


